/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmer
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    
    myDBCon dbCon;
    ResultSet rs;
    
    public AddCustomer() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        CustomerID_Error.setVisible(false);
        Fname_Error.setVisible(false);
        Lname_Error.setVisible(false);
        Address_Error.setVisible(false);
        Sex_Error.setVisible(false);
        Email_Error.setVisible(false);
        PhoneNo_Error.setVisible(false);
        
        //populate sex combo box
        cmbSex.addItem("M");
        cmbSex.addItem("F");
        
        dbCon = new myDBCon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        private void txtJobActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

        private boolean isDuplicate(int cusid) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT CUSTOMERID FROM PROJ_CUSTOMERS WHERE CUSTOMERID = " + cusid;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
    void clearErrorLabels() { // clear all labels used to display error messages 
        CustomerID_Error.setVisible(false);
        Fname_Error.setVisible(false);
        Lname_Error.setVisible(false);
        Address_Error.setVisible(false);
        Sex_Error.setVisible(false);
        Email_Error.setVisible(false);
        PhoneNo_Error.setVisible(false);
    }
    
    boolean isValidData() throws SQLException {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (CustomerID_Field.getText().trim().isEmpty() || !isInteger(CustomerID_Field.getText().trim()) || CustomerID_Field.getText().trim().length() > 38) {
            if (CustomerID_Field.getText().trim().isEmpty()) {
                CustomerID_Error.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(CustomerID_Field.getText().trim())) {
                CustomerID_Error.setText("Invalid. Must be integer.");
            } else if (CustomerID_Field.getText().trim().length() > 38) {
                CustomerID_Error.setText("Invalid. Must be < 38 chars.");
            }
            CustomerID_Error.setVisible(true);
            result = false;
        }

        if (Fname_Field.getText().trim().isEmpty() || (Fname_Field.getText().trim().length() > 15)) {
            if (Fname_Field.getText().trim().isEmpty()) {
                Fname_Error.setText("Invalid. Cannot be empty.");
            } else if ((Fname_Field.getText().trim().length() > 15)) {
                Fname_Error.setText("Invalid. Must be < 15 chars.");
            }
            Fname_Error.setVisible(true);
            result = false;
        }

        if (Lname_Field.getText().trim().isEmpty() || (Lname_Field.getText().trim().length() > 15)) {
            if (Lname_Field.getText().trim().isEmpty()) {
                Lname_Error.setText("Invalid. Cannot be empty.");
            } else if ((Lname_Field.getText().trim().length() > 15)) {
                Lname_Error.setText("Invalid. Must be < 15 chars.");
            }
            Lname_Error.setVisible(true);
            result = false;
        }

        if (Address_Field.getText().trim().isEmpty() || (Address_Field.getText().trim().length() > 100)) {
            if (Address_Field.getText().trim().isEmpty()) {
                Address_Error.setText("Invalid. Cannot be empty.");
            } else if (Address_Field.getText().trim().length() > 100) {
                Address_Error.setText("Invalid. Must be < 100 chars.");
            }
            Address_Error.setVisible(true);
            result = false;
        }
        
        if (Email_Field.getText().trim().isEmpty() || !isValidEmail(Email_Field.getText())) {
            if (Email_Field.getText().trim().isEmpty()) {
                Email_Error.setText("Invalid. Cannot be empty.");
            } else if (!isValidEmail(Email_Field.getText())){
                Email_Error.setText("Email format must be like example@example.com");
            }
            Email_Error.setVisible(true);
            result = false;
        }
                
        if (PhoneNo_Field.getText().trim().isEmpty() || !isValidPhone(PhoneNo_Field.getText()) ) {
            if (PhoneNo_Field.getText().trim().isEmpty()) {
                PhoneNo_Error.setText("Invalid. Cannot be empty.");     
            } else if (!isValidPhone(PhoneNo_Field.getText())){
                PhoneNo_Error.setText("phone number must be like +xxx xxxxxxx");
            }
            PhoneNo_Error.setVisible(true);
            result = false;
        }

        return result;
    }
        
    void clearInputBoxes() { // clear for every new entry 
        
        CustomerID_Field.setText("");
        Fname_Field.setText("");
        Lname_Field.setText("");
        Address_Field.setText("");
        cmbSex.setSelectedIndex(0);
        Email_Field.setText("");
        PhoneNo_Field.setText("");
        
    }
    
    
 private boolean isValidEmail(String email) throws SQLException {
        boolean isValidEmail = false;
        // write code here
        Pattern pattern = Pattern.compile(".+@.+\\..+");
        Matcher matcher = pattern.matcher(email);
        isValidEmail = matcher.matches();

        return isValidEmail;
    }

    private boolean isValidPhone(String phone) throws SQLException {
        boolean isValidPhone = false;
        // write code here
        Pattern pattern = Pattern.compile("\\+\\d+\\s+\\d+");
        Matcher matcher = pattern.matcher(phone);
        isValidPhone = matcher.matches();

        return isValidPhone;
    }
    

        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        CustomerID_Label = new javax.swing.JLabel();
        Fname_Label = new javax.swing.JLabel();
        Lname_Label = new javax.swing.JLabel();
        Address_Label = new javax.swing.JLabel();
        Sex_Label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PhoneNo_Label = new javax.swing.JLabel();
        CustomerID_Field = new javax.swing.JTextField();
        Fname_Field = new javax.swing.JTextField();
        Lname_Field = new javax.swing.JTextField();
        Address_Field = new javax.swing.JTextField();
        Email_Field = new javax.swing.JTextField();
        PhoneNo_Field = new javax.swing.JTextField();
        cmbSex = new javax.swing.JComboBox<>();
        CustomerID_Error = new javax.swing.JLabel();
        Fname_Error = new javax.swing.JLabel();
        Lname_Error = new javax.swing.JLabel();
        Address_Error = new javax.swing.JLabel();
        Sex_Error = new javax.swing.JLabel();
        Email_Error = new javax.swing.JLabel();
        PhoneNo_Error = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(679, 441));

        Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Title.setText("Add New Customer");

        CustomerID_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CustomerID_Label.setText("CUSTOMER ID:");

        Fname_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Fname_Label.setText("FIRST NAME:");

        Lname_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lname_Label.setText("LAST NAME:");

        Address_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Address_Label.setText("ADDRESS:");

        Sex_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sex_Label.setText("SEX:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("EMAIL:");

        PhoneNo_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PhoneNo_Label.setText("PHONE NUMBER:");

        CustomerID_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CustomerID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerID_FieldActionPerformed(evt);
            }
        });

        Fname_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fname_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fname_FieldActionPerformed(evt);
            }
        });

        Lname_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lname_FieldActionPerformed(evt);
            }
        });

        Address_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Address_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address_FieldActionPerformed(evt);
            }
        });

        Email_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_FieldActionPerformed(evt);
            }
        });

        PhoneNo_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PhoneNo_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNo_FieldActionPerformed(evt);
            }
        });

        cmbSex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        CustomerID_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        CustomerID_Error.setForeground(new java.awt.Color(255, 0, 0));
        CustomerID_Error.setText("error label");

        Fname_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Fname_Error.setForeground(new java.awt.Color(255, 0, 0));
        Fname_Error.setText("error label");

        Lname_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Lname_Error.setForeground(new java.awt.Color(255, 0, 0));
        Lname_Error.setText("error label");

        Address_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Address_Error.setForeground(new java.awt.Color(255, 0, 0));
        Address_Error.setText("error label");

        Sex_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Sex_Error.setForeground(new java.awt.Color(255, 0, 0));
        Sex_Error.setText("error label");

        Email_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Email_Error.setForeground(new java.awt.Color(255, 0, 0));
        Email_Error.setText("error label");

        PhoneNo_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        PhoneNo_Error.setForeground(new java.awt.Color(255, 0, 0));
        PhoneNo_Error.setText("error label");

        addButton.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        addButton.setText("Add New");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PhoneNo_Label)
                    .addComponent(Fname_Label)
                    .addComponent(CustomerID_Label)
                    .addComponent(Lname_Label)
                    .addComponent(Address_Label)
                    .addComponent(Sex_Label)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Address_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(Email_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(PhoneNo_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(cmbSex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerID_Field)
                    .addComponent(Fname_Field)
                    .addComponent(Lname_Field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustomerID_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fname_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Lname_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Address_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Sex_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Email_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PhoneNo_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerID_Label)
                    .addComponent(CustomerID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerID_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fname_Label)
                    .addComponent(Fname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname_Label)
                    .addComponent(Lname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address_Label)
                    .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex_Label)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sex_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNo_Label)
                    .addComponent(PhoneNo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNo_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(addButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerID_FieldActionPerformed

    private void Fname_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fname_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fname_FieldActionPerformed

    private void Lname_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lname_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lname_FieldActionPerformed

    private void Address_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Address_FieldActionPerformed

    private void Email_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_FieldActionPerformed

    private void PhoneNo_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNo_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNo_FieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this customer profile?", "Confirmation", JOptionPane.YES_NO_OPTION);

    if (dialogResult == JOptionPane.YES_OPTION) {
        try {
            /*
            * you need also to verify that the empno is unique and not duplicate
            *
            */
            if (isValidData()) {
                    //&& !isDuplicate(Integer.parseInt(CustomerID_Field.getText().trim()))
                // TODO: UPDATE CODE TO WORK FOR SQL IMPLEMENTATION
                String prepSQL = "INSERT INTO PROJ_CUSTOMERS (CustomerID, CFname, CLname, Address, Sex, Email, PhoneNo) VALUES ("
                + CustomerID_Field.getText().trim() + ", "
                + "'" + Fname_Field.getText() + "', "
                + "'" + Lname_Field.getText() + "', "
                + "'" + Address_Field.getText().trim() + "',"        
                + "'" + cmbSex.getSelectedItem().toString() + "', "
                + "'" + Email_Field.getText().trim() + "',"
                + "'" + PhoneNo_Field.getText().trim() + "'"+ ")";
                
                System.out.println(prepSQL);

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New Customer added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }
            if (this.rs != null) {
                rs.close();
            }
            } else {
                
                if (!CustomerID_Field.getText().trim().isEmpty() && isInteger(CustomerID_Field.getText().trim())) {
                    if (!isDuplicate(Integer.parseInt(CustomerID_Field.getText().trim()))) {
                        javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        javax.swing.JLabel label = new javax.swing.JLabel("CustomerNo Already exists. Use a different customerID.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                        // check validation errors
                    }
                }

            }
        } catch (SQLException e) {
            e.printStackTrace(); // This will print the stack trace to the console
            JOptionPane.showMessageDialog(null, "Error adding new customer.");
        }
    }
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_Error;
    private javax.swing.JTextField Address_Field;
    private javax.swing.JLabel Address_Label;
    private javax.swing.JLabel CustomerID_Error;
    private javax.swing.JTextField CustomerID_Field;
    private javax.swing.JLabel CustomerID_Label;
    private javax.swing.JLabel Email_Error;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JLabel Fname_Error;
    private javax.swing.JTextField Fname_Field;
    private javax.swing.JLabel Fname_Label;
    private javax.swing.JLabel Lname_Error;
    private javax.swing.JTextField Lname_Field;
    private javax.swing.JLabel Lname_Label;
    private javax.swing.JLabel PhoneNo_Error;
    private javax.swing.JTextField PhoneNo_Field;
    private javax.swing.JLabel PhoneNo_Label;
    private javax.swing.JLabel Sex_Error;
    private javax.swing.JLabel Sex_Label;
    private javax.swing.JLabel Title;
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> cmbSex;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
