package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class AddColour extends javax.swing.JFrame {

    /**
     * Creates new form AddColour
     */
    myDBCon dbCon;
    ResultSet rs;

    public AddColour() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblColourIDError.setVisible(false);
        ColourNameError.setVisible(false);
        
        dbCon = new myDBCon(); // Initialize dbCon here

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtColourID = new javax.swing.JTextField();
        txtColourName = new javax.swing.JTextField();
        btnAddNewEmp = new javax.swing.JButton();
        lblColourIDError = new javax.swing.JLabel();
        ColourNameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Colour");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Colour ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Colour:");

        txtColourID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtColourID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColourIDActionPerformed(evt);
            }
        });

        txtColourName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAddNewEmp.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        lblColourIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblColourIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblColourIDError.setText("error label");

        ColourNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        ColourNameError.setForeground(new java.awt.Color(255, 0, 0));
        ColourNameError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtColourID)
                    .addComponent(txtColourName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblColourIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ColourNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(btnAddNewEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColourID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblColourIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColourName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ColourNameError))
                .addGap(28, 28, 28)
                .addComponent(btnAddNewEmp)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblColourIDError.setText("");
        lblColourIDError.setVisible(false);
        ColourNameError.setText("");
        ColourNameError.setVisible(false);
        
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtColourID.getText().trim().isEmpty() || !isInteger(txtColourID.getText().trim())) {
            if (txtColourID.getText().trim().isEmpty()) {
                lblColourIDError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtColourID.getText().trim())) {
                lblColourIDError.setText("Invalid. Must be integer.");
            }
            lblColourIDError.setVisible(true);
            result = false;
        }

        if (txtColourName.getText().trim().isEmpty() || (txtColourName.getText().trim().length() > 20)) {
            if (txtColourName.getText().trim().isEmpty()) {
                ColourNameError.setText("Invalid. Cannot be empty.");
            } else if ((txtColourName.getText().trim().length() > 20)) {
                ColourNameError.setText("Invalid. Must be < 20 chars.");
            }
            ColourNameError.setVisible(true);
            result = false;
        }


        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtColourID.setText("");
        txtColourName.setText("");
        
    }

    private boolean isDuplicate(int ColourID) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT ColourID FROM PROJ_COLOURS WHERE ColourID = " + ColourID;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

    int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this colour?", "Confirmation", JOptionPane.YES_NO_OPTION);

    if (dialogResult == JOptionPane.YES_OPTION) {
        try {
            /*
                * you need also to verify that the ColourID is unique and not duplicate 
                *
             */
            if (isValidData() && !isDuplicate(Integer.parseInt(txtColourID.getText().trim()))) {
                // if new employee details are valid, then add new employee to DB

                String prepSQL = "INSERT INTO PROJ_COLOURS (ColourID, Colour) VALUES ("
                        + txtColourID.getText().trim() + ", "
                        + "'" + txtColourName.getText().toUpperCase() + "')";

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New Colour added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                if (!isDuplicate(Integer.parseInt(txtColourID.getText().trim()))) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("ColourID Already exists. Use a different ColourID.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    // check validation errors 
                }

            }
        } catch (SQLException e) {
            e.printStackTrace(); // This will print the stack trace to the console
            JOptionPane.showMessageDialog(null, "Error adding new Colour.");
        }
    }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void txtColourIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColourIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColourIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColourNameError;
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblColourIDError;
    private javax.swing.JTextField txtColourID;
    private javax.swing.JTextField txtColourName;
    // End of variables declaration//GEN-END:variables
}
