        package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static jdbcgui.DateValidator.isValidDateFormat;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;
    ResultSet rs;

    public AddEmployee() {
        
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        Empno_Error.setVisible(false);
        Fname_Error.setVisible(false);
        Dno_Error.setVisible(false);
        Bdate_Error.setVisible(false);
        Salary_Error.setVisible(false);
        Address_Error.setVisible(false);
        Lname_Error.setVisible(false);
        Sex_Error.setVisible(false);
        
        //populate sex combo box
        cmbSex.addItem("M");
        cmbSex.addItem("F");


        try {
            // populate valid dno
            dbCon = new myDBCon();
            rs = dbCon.executeStatement("SELECT Dnumber FROM Proj_Departments ORDER BY Dnumber ASC"); // NEED TO MAKE A DEPARTMENT CLASS FIRST

            // get and populate valid department numbers 
            rs = dbCon.executeStatement("SELECT DISTINCT Dnumber, Dname FROM Proj_Departments ORDER BY Dnumber ASC"); // TODO -- CONFIRM W/ DR. WISSAM -- same here
            while (rs.next()) {
                cmbDno.addItem(rs.getString("dname"));
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EmpID_Field = new javax.swing.JTextField();
        Fname_Field = new javax.swing.JTextField();
        Lname_FIeld = new javax.swing.JTextField();
        Salary_Field = new javax.swing.JTextField();
        Address_Field = new javax.swing.JTextField();
        cmbDno = new javax.swing.JComboBox<>();
        btnAddNewEmp = new javax.swing.JButton();
        BDate_Field = new javax.swing.JFormattedTextField();
        Empno_Error = new javax.swing.JLabel();
        Dno_Error = new javax.swing.JLabel();
        Fname_Error = new javax.swing.JLabel();
        Bdate_Error = new javax.swing.JLabel();
        Salary_Error = new javax.swing.JLabel();
        Address_Error = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Sex_Error = new javax.swing.JLabel();
        Lname_Error = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Employee");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("EMPID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("FNAME:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LNAME:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DNO:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("BDATE:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("SALARY:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ADDRESS:");

        EmpID_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpID_FieldActionPerformed(evt);
            }
        });

        Fname_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Lname_FIeld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname_FIeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lname_FIeldActionPerformed(evt);
            }
        });

        Salary_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Address_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbDno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbDno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDnoActionPerformed(evt);
            }
        });

        btnAddNewEmp.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        BDate_Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MMM-yyyy"))));
        BDate_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Empno_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Empno_Error.setForeground(new java.awt.Color(255, 0, 0));
        Empno_Error.setText("error label");

        Dno_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Dno_Error.setForeground(new java.awt.Color(255, 0, 0));
        Dno_Error.setText("error label");

        Fname_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Fname_Error.setForeground(new java.awt.Color(255, 0, 0));
        Fname_Error.setText("error label");

        Bdate_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Bdate_Error.setForeground(new java.awt.Color(255, 0, 0));
        Bdate_Error.setText("error label");

        Salary_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Salary_Error.setForeground(new java.awt.Color(255, 0, 0));
        Salary_Error.setText("error label");

        Address_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Address_Error.setForeground(new java.awt.Color(255, 0, 0));
        Address_Error.setText("error label");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("SEX:");

        Sex_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Sex_Error.setForeground(new java.awt.Color(255, 0, 0));
        Sex_Error.setText("error label");

        Lname_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Lname_Error.setForeground(new java.awt.Color(255, 0, 0));
        Lname_Error.setText("error label");

        cmbSex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNewEmp)
                            .addComponent(Fname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lname_FIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salary_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Empno_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fname_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dno_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bdate_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salary_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lname_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sex_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EmpID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Empno_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Fname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Lname_FIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dno_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BDate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdate_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Salary_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salary_Error))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Sex_Error)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnAddNewEmp)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lname_FIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lname_FIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lname_FIeldActionPerformed

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        Empno_Error.setText("");
        Empno_Error.setVisible(false);
        Fname_Error.setText("");
        Fname_Error.setVisible(false);
        Lname_Error.setText("");
        Lname_Error.setVisible(false);
        Dno_Error.setText("");
        Dno_Error.setVisible(false);
        Bdate_Error.setText("");
        Bdate_Error.setVisible(false);
        Salary_Error.setText("");
        Salary_Error.setVisible(false);
        Address_Error.setText("");
        Address_Error.setVisible(false);
        Sex_Error.setText("");
        Sex_Error.setVisible(false);
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (EmpID_Field.getText().trim().isEmpty() || !isInteger(EmpID_Field.getText().trim())) {
            if (EmpID_Field.getText().trim().isEmpty()) {
                Empno_Error.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(EmpID_Field.getText().trim())) {
                Empno_Error.setText("Invalid. Must be integer.");
            }
            Empno_Error.setVisible(true);
            result = false;
        }

        if (Fname_Field.getText().trim().isEmpty() || (Fname_Field.getText().trim().length() > 15)) {
            if (Fname_Field.getText().trim().isEmpty()) {
                Fname_Error.setText("Invalid. Cannot be empty.");
            } else if ((Fname_Field.getText().trim().length() > 15)) {
                Fname_Error.setText("Invalid. Must be < 15 chars.");
            }
            Fname_Error.setVisible(true);
            result = false;
        }

        if (Lname_FIeld.getText().trim().isEmpty() || (Lname_FIeld.getText().trim().length() > 15)) {
            if (Lname_FIeld.getText().trim().isEmpty()) {
                Lname_Error.setText("Invalid. Cannot be empty.");
            } else if (Lname_FIeld.getText().trim().length() > 15) {
                Lname_Error.setText("Invalid. Must be < 15 chars.");
            }
            Lname_Error.setVisible(true);
            result = false;
        }

        if (BDate_Field.getText().trim().isEmpty() || !isValidDateFormat(BDate_Field.getText())) {
            if (BDate_Field.getText().trim().isEmpty() ){
            Bdate_Error.setText("Invalid. Cannot be empty.");
            Bdate_Error.setVisible(true);
            } else if(!isValidDateFormat(BDate_Field.getText())){
                Bdate_Error.setText("Invalid. Date must be DD-MMM-YYYY.");
                Bdate_Error.setVisible(true);
            }
            result = false;
        }

        if (Salary_Field.getText().trim().isEmpty() || !(isInteger(Salary_Field.getText().trim()) || isDouble(Salary_Field.getText().trim()))) {
            if (Salary_Field.getText().trim().isEmpty()) {
                Salary_Error.setText("Invalid. Cannot be empty.");
            } else if (!(isInteger(Salary_Field.getText().trim()) || isDouble(Salary_Field.getText().trim()))) {
                Salary_Error.setText("Invalid. Must be number.");
            }
            Salary_Error.setVisible(true);
            result = false;
        }

        if (Address_Field.getText().trim().isEmpty() || (Address_Field.getText().trim().length() > 100)) {
            if (Lname_FIeld.getText().trim().isEmpty()) {
                Address_Error.setText("Invalid. Cannot be empty.");
            } else if (Address_Field.getText().trim().length() > 100) {
                Address_Error.setText("Invalid. Must be < 100 chars.");
            }
            Address_Error.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        EmpID_Field.setText("");
        Fname_Field.setText("");
        Lname_FIeld.setText("");
        BDate_Field.setText("");
        Salary_Field.setText("");
        Address_Field.setText("");
        cmbDno.setSelectedIndex(0);
        cmbDno.setSelectedIndex(0);
    }

    private boolean isDuplicate(int empno) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT empno FROM emp WHERE empno = " + empno;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:
                // Show confirmation dialog
    int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this employee?", "Confirmation", JOptionPane.YES_NO_OPTION);

    if (dialogResult == JOptionPane.YES_OPTION) {
        
        try {
            /*
                * you need also to verify that the empno is unique and not duplicate 
                *
             */
            if (isValidData() && !isDuplicate(Integer.parseInt(EmpID_Field.getText().trim()))) {
                // if new employee details are valid, then add new employee to DB

                String prepSQL = "INSERT INTO emp (empid, fname, lname, bdate, address, sex, salary, dno) VALUES ("
                        + EmpID_Field.getText().trim() + ", "
                        + "'" + Fname_Field.getText().toUpperCase() + "', "
                        + "'" + Lname_FIeld.getText().toUpperCase() + "', "
                        + "'" + BDate_Field.getText().trim() + "',"
                        + Address_Field.getText() + ","
                        + cmbSex.getSelectedIndex() + ","
                        + Salary_Field.getText() + ","
                        + cmbDno.getSelectedItem().toString() + ", ";

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New Employee Added Successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                    if (!EmpID_Field.getText().trim().isEmpty() && isInteger(EmpID_Field.getText().trim())) {
                    if (!isDuplicate(Integer.parseInt(EmpID_Field.getText().trim()))) {
                        javax.swing.JLabel label = new javax.swing.JLabel("Please Fix Validation Errors...");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        javax.swing.JLabel label = new javax.swing.JLabel("Empno Already exists. Use a Different Employee Number.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                        // check validation errors 
                    }
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error Adding New Employee.");
        }
    }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void EmpID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpID_FieldActionPerformed

    private void cmbDnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDnoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_Error;
    private javax.swing.JTextField Address_Field;
    private javax.swing.JFormattedTextField BDate_Field;
    private javax.swing.JLabel Bdate_Error;
    private javax.swing.JLabel Dno_Error;
    private javax.swing.JTextField EmpID_Field;
    private javax.swing.JLabel Empno_Error;
    private javax.swing.JLabel Fname_Error;
    private javax.swing.JTextField Fname_Field;
    private javax.swing.JLabel Lname_Error;
    private javax.swing.JTextField Lname_FIeld;
    private javax.swing.JLabel Salary_Error;
    private javax.swing.JTextField Salary_Field;
    private javax.swing.JLabel Sex_Error;
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbDno;
    private javax.swing.JComboBox<String> cmbSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    
}
