package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class AddModel extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;
    ResultSet rs;

    public AddModel() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblModelIDError.setVisible(false);
        lblMakeError.setVisible(false);
        lblNameError.setVisible(false);
        lblYearError.setVisible(false);
        lblPriceError.setVisible(false);

        try {//populate Colour and Type combo boxes 
            // populate valid mgr numbers 
            dbCon = new myDBCon();
            rs = dbCon.executeStatement("SELECT ColourID, Colour FROM PROJ_Colours ORDER BY ColourID ASC");
            // populate colour combo box
            while (rs.next()) { 
                cmbColour.addItem(rs.getString("ColourID"));
            }
            // get and populate valid type
            rs = dbCon.executeStatement("SELECT TypeID, Type FROM PROJ_Types ORDER BY TypeID ASC");
            while (rs.next()) {
                cmbType.addItem(rs.getString("TypeID"));
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtModelID = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        cmbColour = new javax.swing.JComboBox<>();
        cmbType = new javax.swing.JComboBox<>();
        btnAddNewModel = new javax.swing.JButton();
        lblModelIDError = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        lblMakeError = new javax.swing.JLabel();
        lblYearError = new javax.swing.JLabel();
        lblPriceError = new javax.swing.JLabel();
        ftxtYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Model");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Model ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Make:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Colour:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Year:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Price:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Type:");

        txtModelID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtModelID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelIDActionPerformed(evt);
            }
        });

        txtMake.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        Price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbColour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAddNewModel.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewModel.setText("Add New");
        btnAddNewModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewModelActionPerformed(evt);
            }
        });

        lblModelIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblModelIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblModelIDError.setText("error label");

        lblNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblNameError.setText("error label");

        lblMakeError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblMakeError.setForeground(new java.awt.Color(255, 0, 0));
        lblMakeError.setText("error label");

        lblYearError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblYearError.setForeground(new java.awt.Color(255, 0, 0));
        lblYearError.setText("error label");

        lblPriceError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPriceError.setForeground(new java.awt.Color(255, 0, 0));
        lblPriceError.setText("error label");

        ftxtYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ftxtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ftxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblYearError, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Price)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblPriceError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAddNewModel)
                                        .addComponent(txtMake, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(Name))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMakeError, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtModelID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblModelIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMakeError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblYearError)
                        .addComponent(ftxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cmbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPriceError))
                .addGap(126, 126, 126)
                .addComponent(btnAddNewModel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblModelIDError.setText("");
        lblModelIDError.setVisible(false);
        lblMakeError.setText("");
        lblMakeError.setVisible(false);
        lblNameError.setText("");
        lblNameError.setVisible(false);
        lblYearError.setText("");
        lblYearError.setVisible(false);
        lblPriceError.setText("");
        lblPriceError.setVisible(false);
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtModelID.getText().trim().isEmpty() || !isInteger(txtModelID.getText().trim())) {
            if (txtModelID.getText().trim().isEmpty()) {
                lblModelIDError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtModelID.getText().trim())) {
                lblModelIDError.setText("Invalid. Must be integer.");
            }
            lblModelIDError.setVisible(true);
            result = false;
        }

        if (txtMake.getText().trim().isEmpty() || (txtMake.getText().trim().length() > 20)) {
            if (txtMake.getText().trim().isEmpty()) {
                lblMakeError.setText("Invalid. Cannot be empty.");
            } else if ((txtMake.getText().trim().length() > 20)) {
                lblMakeError.setText("Invalid. Must be < 20 chars.");
            }
            lblMakeError.setVisible(true);
            result = false;
        }

        if (Name.getText().trim().isEmpty() || (Name.getText().trim().length() > 20)) {
            if (Name.getText().trim().isEmpty()) {
                lblNameError.setText("Invalid. Cannot be empty.");
            } else if (Name.getText().trim().length() > 20) {
                lblNameError.setText("Invalid. Must be < 20 chars.");
            }
            lblNameError.setVisible(true);
            result = false;
        }

        if (ftxtYear.getText().trim().isEmpty() || !isInteger(ftxtYear.getText().trim()) ) {
            lblYearError.setText("Invalid. Cannot be empty/Must be Number.");                   
            lblYearError.setVisible(true);
            
            result = false;
        }

        if (Price.getText().trim().isEmpty() || !(isInteger(Price.getText().trim()) || isDouble(Price.getText().trim()))) {
            if (Price.getText().trim().isEmpty()) {
                lblPriceError.setText("Invalid. Cannot be empty.");
            } else if (!(isInteger(Price.getText().trim()) || isDouble(Price.getText().trim()))) {
                lblPriceError.setText("Invalid. Must be number.");
            }
            lblPriceError.setVisible(true);
            result = false;
        }

        

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtModelID.setText("");
        txtMake.setText("");
        Name.setText("");
        ftxtYear.setText("");
        Price.setText("");
        cmbType.setSelectedIndex(0);
        cmbColour.setSelectedIndex(0);
    }

    private boolean isDuplicate(int ModelID) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT ModelID FROM Proj_Models WHERE ModelID = " + ModelID;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewModelActionPerformed
        // TODO add your handling code here:
    int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this model?", "Confirmation", JOptionPane.YES_NO_OPTION);

    if (dialogResult == JOptionPane.YES_OPTION) {
        try {
            /*
                * you need also to verify that the ModelID is unique and not duplicate 
                *
             */
            if (isValidData() && !isDuplicate(Integer.parseInt(txtModelID.getText().trim()))) {
                // if new employee details are valid, then add new employee to DB

                String prepSQL = "INSERT INTO PROJ_MODELS (ModelID, Make, name, year, colourid, typeid, price) VALUES ("
                        + txtModelID.getText().trim() + ", "
                        + "'" + txtMake.getText().toUpperCase() + "', "
                        + "'" + Name.getText().toUpperCase() + "', "
                        + ftxtYear.getText().trim() + ","
                        + cmbColour.getSelectedItem() + ", "
                        + cmbType.getSelectedItem() + ", "
                        + Price.getText() + ")";

                System.out.println(prepSQL);
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New Model added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                if (!txtModelID.getText().trim().isEmpty() && isInteger(txtModelID.getText().trim())) {
                    if (!isDuplicate(Integer.parseInt(txtModelID.getText().trim()))) {
                        javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        javax.swing.JLabel label = new javax.swing.JLabel("ModelID Already exists. Use a different ModelID.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                        // check validation errors 
                    }
                }

            }
        } catch (SQLException e) {
            e.printStackTrace(); // This will print the stack trace to the console
            JOptionPane.showMessageDialog(null, "Error adding new Model.");
        }
    }
    }//GEN-LAST:event_btnAddNewModelActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void txtModelIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelIDActionPerformed

    private void ftxtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Price;
    private javax.swing.JButton btnAddNewModel;
    private javax.swing.JComboBox<String> cmbColour;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JTextField ftxtYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMakeError;
    private javax.swing.JLabel lblModelIDError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPriceError;
    private javax.swing.JLabel lblYearError;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModelID;
    // End of variables declaration//GEN-END:variables
}
