/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static jdbcgui.DateValidator.isValidDateFormat;

/**
 *
 * @author Ahmer
 */
public class AddSales extends javax.swing.JFrame {

    /**
     * Creates new form AddSales
     */
    
    myDBCon dbCon;
    ResultSet rs;
    public AddSales() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        SaleID_Error.setVisible(false);
        VIN_Error.setVisible(false);
        Date_Error.setVisible(false);
        Warranty_Error.setVisible(false);
        EmpID_Error.setVisible(false);
        
        
        try {
            // populate valid dno
            dbCon = new myDBCon();
            rs = dbCon.executeStatement("SELECT VIN FROM Proj_Vehicles ORDER BY VIN ASC"); // NEED VIN TABLE
            // get and populate valid department numbers 
            while (rs.next()) {
                cmbVin.addItem(rs.getString("VIN"));
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        try {
            // populate valid dno
            dbCon = new myDBCon();
            // get and populate valid department numbers 
            rs = dbCon.executeStatement("SELECT EmpID FROM PROJ_EMPLOYEES ORDER BY EmpID ASC"); // TODO -- CONFIRM W/ DR. WISSAM -- same here
            while (rs.next()) {
                cmbEmpID.addItem(rs.getString("EmpID"));
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        SaleID_Error.setText("");
        SaleID_Error.setVisible(false);
        VIN_Error.setText("");
        VIN_Error.setVisible(false);
        Date_Error.setText("");
        Date_Error.setVisible(false);
        Warranty_Error.setText("");
        Warranty_Error.setVisible(false);
        EmpID_Error.setText("");
        EmpID_Error.setVisible(false);
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (SaleID_Field.getText().trim().isEmpty() || !isInteger(SaleID_Field.getText().trim())) {
            if (SaleID_Field.getText().trim().isEmpty()) {
                SaleID_Error.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(SaleID_Field.getText().trim())) {
                SaleID_Error.setText("Invalid. Must be integer.");
            }
            SaleID_Error.setVisible(true);
            result = false;
        }

        if (Date_Field.getText().trim().isEmpty() || !isValidDateFormat(Date_Field.getText())) {
            if (Date_Field.getText().trim().isEmpty()){
            Date_Error.setText("Invalid. Cannot be empty.");
            Date_Error.setVisible(true);
            } else if (!isValidDateFormat(Date_Field.getText())){
                Date_Error.setText("Invalid. Date must be DD-MMM-YYYY.");
                Date_Error.setVisible(true);
            }
            result = false;
        }


        if (Warranty_Field.getText().trim().isEmpty()) {
            Warranty_Error.setText("Invalid. Cannot be empty.");
            Warranty_Error.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        
        SaleID_Field.setText("");
        cmbVin.setSelectedIndex(0);
        Date_Field.setText("");
        Warranty_Field.setText("");
        cmbEmpID.setSelectedIndex(0);
    }

    private boolean isDuplicate(int saleID) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT SaleID FROM PROJ_SALES WHERE SaleID = " + saleID;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SaleID_Label = new javax.swing.JLabel();
        VIN_Label = new javax.swing.JLabel();
        BDate_Label = new javax.swing.JLabel();
        Warranty_Label = new javax.swing.JLabel();
        SaleID_Field = new javax.swing.JTextField();
        cmbVin = new javax.swing.JComboBox<>();
        Warranty_Field = new javax.swing.JTextField();
        SaleID_Error = new javax.swing.JLabel();
        VIN_Error = new javax.swing.JLabel();
        Date_Error = new javax.swing.JLabel();
        Warranty_Error = new javax.swing.JLabel();
        btnAddNewEmp = new javax.swing.JButton();
        cmbEmpID = new javax.swing.JComboBox<>();
        EmpID_Label = new javax.swing.JLabel();
        EmpID_Error = new javax.swing.JLabel();
        Date_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Sales");

        SaleID_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaleID_Label.setText("SALEID:");

        VIN_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VIN_Label.setText("VIN:");

        BDate_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BDate_Label.setText("DATE:");

        Warranty_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Warranty_Label.setText("WARRANTY:");

        SaleID_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbVin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVinActionPerformed(evt);
            }
        });

        Warranty_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SaleID_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        SaleID_Error.setForeground(new java.awt.Color(255, 0, 0));
        SaleID_Error.setText("error label");

        VIN_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        VIN_Error.setForeground(new java.awt.Color(255, 0, 0));
        VIN_Error.setText("error label");

        Date_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Date_Error.setForeground(new java.awt.Color(255, 0, 0));
        Date_Error.setText("error label");

        Warranty_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Warranty_Error.setForeground(new java.awt.Color(255, 0, 0));
        Warranty_Error.setText("error label");

        btnAddNewEmp.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        cmbEmpID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpIDActionPerformed(evt);
            }
        });

        EmpID_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpID_Label.setText("EMPID:");

        EmpID_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        EmpID_Error.setForeground(new java.awt.Color(255, 0, 0));
        EmpID_Error.setText("error label");

        Date_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SaleID_Label)
                            .addComponent(VIN_Label)
                            .addComponent(BDate_Label)
                            .addComponent(Warranty_Label)
                            .addComponent(EmpID_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNewEmp)
                            .addComponent(SaleID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Warranty_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpID_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaleID_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Warranty_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VIN_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaleID_Label)
                    .addComponent(SaleID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaleID_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VIN_Label)
                    .addComponent(cmbVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VIN_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDate_Label)
                    .addComponent(Date_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Warranty_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Warranty_Label)
                    .addComponent(Warranty_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpID_Label)
                    .addComponent(cmbEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpID_Error))
                .addGap(36, 36, 36)
                .addComponent(btnAddNewEmp)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVinActionPerformed

    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:
    int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this sale?", "Confirmation", JOptionPane.YES_NO_OPTION);

    if (dialogResult == JOptionPane.YES_OPTION) {
        try {
            /*
            * you need also to verify that the empno is unique and not duplicate
            *
            */
            if (isValidData() && !isDuplicate(Integer.parseInt(SaleID_Field.getText().trim()))) {
                // if new employee details are valid, then add new employee to DB

                String prepSQL = "INSERT INTO PROJ_SALES (SaleID, VIN, SDATE, WARRANTYYEARS, EMPID) VALUES ("
                + SaleID_Field.getText().trim() + ", "
                + cmbVin.getSelectedItem() + ","
                + "'" + Date_Field.getText().trim() + "',"
                + Warranty_Field.getText() + ","        
                + cmbEmpID.getSelectedItem() + ")";
                
                System.out.println(prepSQL);

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New Sale Added Successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                 if (!SaleID_Field.getText().trim().isEmpty() && isInteger(SaleID_Field.getText().trim())) {
                        if (!isDuplicate(Integer.parseInt(SaleID_Field.getText().trim()))) {
                        javax.swing.JLabel label = new javax.swing.JLabel("Please Fix Validation Errors...");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        javax.swing.JLabel label = new javax.swing.JLabel("SaleID Already exists. Use a Different SaleID.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                        // check validation errors
                    }
                 }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error Adding New Sales.");
        }
    }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void cmbEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BDate_Label;
    private javax.swing.JLabel Date_Error;
    private javax.swing.JTextField Date_Field;
    private javax.swing.JLabel EmpID_Error;
    private javax.swing.JLabel EmpID_Label;
    private javax.swing.JLabel SaleID_Error;
    private javax.swing.JTextField SaleID_Field;
    private javax.swing.JLabel SaleID_Label;
    private javax.swing.JLabel VIN_Error;
    private javax.swing.JLabel VIN_Label;
    private javax.swing.JLabel Warranty_Error;
    private javax.swing.JTextField Warranty_Field;
    private javax.swing.JLabel Warranty_Label;
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbEmpID;
    private javax.swing.JComboBox<String> cmbVin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
