/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbcgui;

/**
 *
 * @author Ahmer
 */


import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;



public class AddVehicles extends javax.swing.JFrame {

    /**
     * Creates new form AddVehicles
     */
    
    myDBCon dbCon;
    ResultSet rs;
    
    public AddVehicles() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        VIN_Error.setVisible(false);
        ModelID_Error.setVisible(false);
        
        try {//populate Colour and Type combo boxes 
            // populate valid mgr numbers 
            dbCon = new myDBCon();
            rs = dbCon.executeStatement("SELECT MODELID FROM PROJ_Models ORDER BY MODELID ASC");
            // populate colour combo box
            while (rs.next()) { 
                cmbModelID.addItem(rs.getString("MODELID"));
            }
            // get and populate valid type
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    void clearErrorLabels() { // clear all labels used to display error messages 
        VIN_Error.setText("");
        VIN_Error.setVisible(false);
        ModelID_Error.setText("");
        ModelID_Error.setVisible(false);
        
    }
    
    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (VIN_Field.getText().trim().isEmpty() || !isInteger(VIN_Field.getText().trim())) {
            if (VIN_Field.getText().trim().isEmpty()) {
                VIN_Error.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(VIN_Field.getText().trim())) {
                VIN_Error.setText("Invalid. Must be integer.");
            }
            VIN_Error.setVisible(true);
            result = false;
        }


        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        VIN_Field.setText("");
        cmbModelID.setSelectedIndex(0);
        
    }

    private boolean isDuplicate(int vin) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT VIN FROM PROJ_VEHICLES WHERE VIN= " + vin;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VIN_Label = new javax.swing.JLabel();
        VIN_Field = new javax.swing.JTextField();
        VIN_Error = new javax.swing.JLabel();
        ModelID_Label = new javax.swing.JLabel();
        cmbModelID = new javax.swing.JComboBox<>();
        ModelID_Error = new javax.swing.JLabel();
        btnAddNewEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Vehicle");

        VIN_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VIN_Label.setText("VIN:");

        VIN_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        VIN_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        VIN_Error.setForeground(new java.awt.Color(255, 0, 0));
        VIN_Error.setText("error label");

        ModelID_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ModelID_Label.setText("MODELID:");

        cmbModelID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbModelID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModelIDActionPerformed(evt);
            }
        });

        ModelID_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        ModelID_Error.setForeground(new java.awt.Color(255, 0, 0));
        ModelID_Error.setText("error label");

        btnAddNewEmp.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VIN_Label)
                            .addComponent(ModelID_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VIN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbModelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddNewEmp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VIN_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModelID_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VIN_Label)
                    .addComponent(VIN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VIN_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModelID_Label)
                    .addComponent(cmbModelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModelID_Error))
                .addGap(31, 31, 31)
                .addComponent(btnAddNewEmp)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbModelIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModelIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbModelIDActionPerformed

    
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:
        
    int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this vehicle?", "Confirmation", JOptionPane.YES_NO_OPTION);

    if (dialogResult == JOptionPane.YES_OPTION) {
            try {
            /*
                * you need also to verify that the ModelID is unique and not duplicate 
                *
             */
            if (isValidData() && !isDuplicate(Integer.parseInt(VIN_Field.getText().trim()))) {
                // if new employee details are valid, then add new employee to DB

                String prepSQL = "INSERT INTO PROJ_VEHICLES (VIN, ModelID) VALUES ("
                        + VIN_Field.getText().trim() + ", "
                        + cmbModelID.getSelectedIndex() + ")";

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New Vehicle added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                if (!VIN_Field.getText().trim().isEmpty() && isInteger(VIN_Field.getText().trim())) {

                if (!isDuplicate(Integer.parseInt(VIN_Field.getText().trim()))) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("VIN Already exists. Use a different VIN.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    // check validation errors 
                }
                                    }

            }
        } catch (SQLException e) {
            e.printStackTrace(); // This will print the stack trace to the console
            JOptionPane.showMessageDialog(null, "Error adding new Vehicle.");
        }
    }
                                                  
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehicles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ModelID_Error;
    private javax.swing.JLabel ModelID_Label;
    private javax.swing.JLabel VIN_Error;
    private javax.swing.JTextField VIN_Field;
    private javax.swing.JLabel VIN_Label;
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbModelID;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
