package jdbcgui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

//This class is used to update and delete the department

public class UpdateDeleteDept extends javax.swing.JFrame {
    //instantiate a database connection
    myDBCon dbCon = new myDBCon();
    Statement statement;
    PreparedStatement prepStatement;
    ResultSet rs;
    ResultSet rsdeptno;

    public UpdateDeleteDept() {
        initComponents();
        // center form in screen 
        this.setLocationRelativeTo(null);
        //set all error flags invisible 
        lblDeptnoError.setVisible(false);
        lblDnameError.setVisible(false);
        lblLocError.setVisible(false);
        //populate fields 
        getNewData();

    }

    private void getNewData() {
        try{
            rsdeptno = dbCon.executeStatement("SELECT DEPTNO, DNAME, LOC FROM DEPT ORDER BY DEPTNO ASC ");
            rsdeptno.beforeFirst();
            rsdeptno.first();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - GetNewData() in UpdateDeleteDepartment.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
   // populate all the fields
   populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        txtDeptno = new javax.swing.JTextField();
        lblDeptnoError = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDeptno1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLoc = new javax.swing.JTextField();
        lblDnameError = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDname = new javax.swing.JTextField();
        lblLocError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Employee");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Department");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("DEPTNO:");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        txtDeptno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDeptno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptnoActionPerformed(evt);
            }
        });

        lblDeptnoError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDeptnoError.setForeground(new java.awt.Color(255, 0, 0));
        lblDeptnoError.setText("error label");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Prev_DEPTNO:");

        txtDeptno1.setEditable(false);
        txtDeptno1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDeptno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptno1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("LOC:");

        txtLoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocActionPerformed(evt);
            }
        });

        lblDnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblDnameError.setText("error label");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("DNAME:");

        txtDname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDnameActionPerformed(evt);
            }
        });

        lblLocError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblLocError.setForeground(new java.awt.Color(255, 0, 0));
        lblLocError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDeptno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDeptnoError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDeptno1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDnameError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLocError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDeptno1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDeptno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDeptnoError)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDnameError)
                    .addComponent(jLabel12)
                    .addComponent(txtDname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnNext)
                            .addComponent(btnPrevious)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLocError)
                            .addComponent(jLabel11))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            txtDeptno.setText(rsdeptno.getString("deptno"));
            txtDeptno1.setText(rsdeptno.getString("deptno"));
            txtLoc.setText(rsdeptno.getString("loc"));
            txtDname.setText(rsdeptno.getString("dname"));
            
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteDept.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() {
        try {
            //Move to next row if not last row
            if (!rsdeptno.isLast()) {

                rsdeptno.next();
                populateFields();

            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteDept.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void MovePrevious() {
        try {
            //Move to previous row if not first row
            if (!rsdeptno.isFirst()) {
                rsdeptno.previous();
                populateFields();

            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteDept.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            //Disable previous button if first row
            if (rsdeptno.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            //Disable previous button if last row
            if (rsdeptno.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteDept.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // confirm if user wants to delete or not
            int confirmDelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this department?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if(confirmDelete != JOptionPane.YES_OPTION){
            //if user doesn't click yes, do nothing
            return;
        } 
         try {
            //check if there is any employee in the department 
            ResultSet check = dbCon.executeStatement("SELECT EMPNO FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND D.DEPTNO LIKE '" +  txtDeptno1.getText().trim() + "'");
            if(check.next()){
                //Notify the user that there are employees in the department 
                javax.swing.JLabel label = new javax.swing.JLabel("Can't delete a department with employees in it!");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            try {
            //Delete Department from table
            String sqlCmd = "DELETE FROM DEPT WHERE DEPTNO LIKE '" +  txtDeptno1.getText().trim() + "'";
            int result = dbCon.executePrepared(sqlCmd);
            if (result > 0) {
                javax.swing.JLabel label = new javax.swing.JLabel("Department deleted successfully.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                getNewData();
            }

            }
            catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting department. Restrictions apply");

        }
            

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting department.");

        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    void clearErrorLabels() {
        lblDeptnoError.setText("");
        lblDeptnoError.setVisible(false);

    }

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    boolean isValidData() {
        clearErrorLabels();
        boolean result = true;
        //DeptNo validation check       
        if (!isInteger(txtDeptno.getText().trim()) || txtDeptno.getText().trim().isEmpty()) {
        if (txtDeptno.getText().trim().isEmpty()) {
                lblDeptnoError.setText("Invalid. Cannot be empty.");
            } else if (!(isInteger(txtDeptno.getText().trim()))) {
                lblDeptnoError.setText("Invalid. Must be a number.");
            }

            lblDeptnoError.setVisible(true);
            result = false;
        }
        if (txtDname.getText().trim().isEmpty() || (txtDname.getText().trim().length() > 10)) {
            if (txtDname.getText().trim().isEmpty()) {
                lblDnameError.setText("Invalid. Cannot be empty.");
            } else if ((txtDname.getText().trim().length() > 10)) {
                lblDnameError.setText("Invalid. Must be < 10 chars.");
            }

            lblDnameError.setVisible(true);
            result = false;
        }
        if (txtLoc.getText().trim().isEmpty() || (txtLoc.getText().trim().length() > 10)) {
            if (txtLoc.getText().trim().isEmpty()) {
                lblLocError.setText("Invalid. Cannot be empty.");
            } else if ((txtLoc.getText().trim().length() > 10)) {
                lblLocError.setText("Invalid. Must be < 10 chars.");
            }

            lblLocError.setVisible(true);
            result = false;
        }
        
        //Return true if valid fields and false if invalid fields
        return result;
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         // TODO add your handling code here:
             int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this employee?", "Confirmation", JOptionPane.YES_NO_OPTION);

    if (dialogResult == JOptionPane.YES_OPTION) {
         
        try {
            if (isValidData()) {
                // confirm if user wants to update or not
                int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this department?", "Confirm Update", JOptionPane.YES_NO_OPTION);
                if (confirmUpdate == JOptionPane.YES_OPTION)
                {
                    String prepSQL = "UPDATE DEPT SET DEPTNO = '" + 
                        txtDeptno.getText().trim() + 
                        "', DNAME = '" + txtDname.getText().trim().toUpperCase()+"', LOC = '" + txtLoc.getText().trim().toUpperCase() +"' WHERE DEPTNO = " + txtDeptno1.getText().trim(); 
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Department updated successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    getNewData();
                } else {
                    // check validation errors 
                }
//                prepStatement.close();
                }
                
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating department. Restrictions apply" + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    }
    private void txtDeptnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeptnoActionPerformed

    private void txtDeptno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeptno1ActionPerformed

    private void txtLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocActionPerformed

    private void txtDnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDeptnoError;
    private javax.swing.JLabel lblDnameError;
    private javax.swing.JLabel lblLocError;
    private javax.swing.JTextField txtDeptno;
    private javax.swing.JTextField txtDeptno1;
    private javax.swing.JTextField txtDname;
    private javax.swing.JTextField txtLoc;
    // End of variables declaration//GEN-END:variables
}



