package jdbcgui;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class UpdateDeleteModels extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;

    ResultSet rs;
    ResultSet rsType;
    ResultSet rsColour;

    public UpdateDeleteModels() { // ?
        initComponents();
        // center form in screen 
        //this.setLocationRelativeTo(null); // causing issue
        
        // set all error labels to invisible
        Make_Error.setText("");
        Make_Error.setVisible(false);
        Name_Error.setText("");
        Name_Error.setVisible(false);
        Year_Error.setText("");
        Year_Error.setVisible(false);
        Price_Error.setText("");
        Price_Error.setVisible(false);
        
        
        
        try {//populate the user types 
            dbCon = new myDBCon();
            rsColour = dbCon.executeStatement("SELECT colourid FROM proj_colours ORDER BY colourid ASC"); // CHANGE THIS
            while (rsColour.next()) {
                cmbColour.addItem(rsColour.getString("colourid"));
            }
            
            rsColour.close();
            
            dbCon = new myDBCon();
            rsType = dbCon.executeStatement("SELECT typeid FROM proj_types ORDER BY typeid ASC"); // CHANGE THIS
            while (rsType.next()) {
                cmbType.addItem(rsType.getString("typeid"));
            }
            
            rsType.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        // connect to db and get user data and populate form fields
        dbCon = new myDBCon();
        getNewData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Make_Field = new javax.swing.JTextField();
        ModelID_Field = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        btnUpdateUser = new javax.swing.JButton();
        Make_Error = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Name_Field = new javax.swing.JTextField();
        Name_Error = new javax.swing.JLabel();
        Year_Error = new javax.swing.JLabel();
        Year_Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbColour = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        Price_Field = new javax.swing.JTextField();
        Price_Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Login User");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update Models");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Make:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Type:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ModelID:");

        Make_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ModelID_Field.setEditable(false);
        ModelID_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        btnUpdateUser.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdateUser.setText("Update");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        Make_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Make_Error.setForeground(new java.awt.Color(255, 0, 0));
        Make_Error.setText("error label");

        btnDeleteUser.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDeleteUser.setText("Delete");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Name:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Name_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Name_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Name_Error.setForeground(new java.awt.Color(255, 0, 0));
        Name_Error.setText("error label");

        Year_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Year_Error.setForeground(new java.awt.Color(255, 0, 0));
        Year_Error.setText("error label");

        Year_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Year:");

        cmbColour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColourActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Colour:");

        PriceLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PriceLabel.setText("Price:");

        Price_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Price_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Price_Error.setForeground(new java.awt.Color(255, 0, 0));
        Price_Error.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(410, 410, 410))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                .addGap(381, 381, 381)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
                            .addComponent(PriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Year_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Year_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Price_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ModelID_Field)
                                    .addComponent(Make_Field)
                                    .addComponent(Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Make_Error, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                    .addComponent(Name_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ModelID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Make_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Make_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Year_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLabel)
                    .addComponent(Price_Error)
                    .addComponent(Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getNewData() {
        // get all user data and populate fields 
        try {
            rs = dbCon.executeStatement("SELECT modelid, make, name, year, colourid, typeid, price FROM proj_models ORDER BY modelid ASC ");
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void populateFields() {
        // populate fields with the current user details 
         try {
            //populate fiels from ResultSet data
            ModelID_Field.setText(rs.getString("modelid"));
            Make_Field.setText(rs.getString("make"));
            Name_Field.setText(rs.getString("name"));
            Year_Field.setText(rs.getString("year"));
            Price_Field.setText(rs.getString("price"));



            EnableDisableButtons();
        } catch (SQLException e) {
            Logger.getLogger(UpdateDeleteModels.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }

    private void EnableDisableButtons() {
        // enable/disable Previous/Next buttons
         try {
            //enable previous and next if first and last row are not shown
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException e) {
            Logger.getLogger(UpdateDeleteModels.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    void clearErrorLabels() {
        // clear all error labels and set their visibility to false 
        Make_Error.setText("");
        Make_Error.setVisible(false);
        Name_Error.setText("");
        Name_Error.setVisible(false);
        Year_Error.setText("");
        Year_Error.setVisible(false);

    }

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

       public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    boolean isValidData() {
        // check validity of new data before update 
        clearErrorLabels();
        boolean result = true;
        //check if username is valid
        if (Make_Field.getText().trim().isEmpty() || (Make_Field.getText().trim().length() > 25)) {
            if (Make_Field.getText().trim().isEmpty()) {
                Make_Error.setText("Invalid. Cannot be empty.");
            } else if ((Make_Field.getText().trim().length() > 25)) {
                Make_Error.setText("Invalid. Must be < 25 chars.");
            }

            Make_Error.setVisible(true);
            result = false;
        }
        
        if (Name_Field.getText().trim().isEmpty() || (Name_Field.getText().trim().length() > 25)) {
            if (Name_Field.getText().trim().isEmpty()) {
                Name_Error.setText("Invalid. Cannot be empty.");
            } else if ((Name_Field.getText().trim().length() > 25)) {
                Name_Error.setText("Invalid. Must be < 25 chars.");
            }

            Name_Error.setVisible(true);
            result = false;
        }
             
        if (Year_Field.getText().trim().isEmpty() || (Year_Field.getText().trim().length() != 4)  || !isInteger(Year_Field.getText().trim())) {
            if (Year_Field.getText().trim().isEmpty()) {
                Year_Error.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(Year_Field.getText().trim())) {
                Year_Error.setText("Invalid. Must be an integer.");
            } else if ((Year_Field.getText().trim().length() != 4)) {
                Year_Error.setText("Invalid. Must be < 4 chars.");
            }

            Year_Error.setVisible(true);
            result = false;
        }
       
        
        if (Price_Field.getText().trim().isEmpty() || !(isInteger(Price_Field.getText().trim()) || isDouble(Price_Field.getText().trim()))) {
            if (Price_Field.getText().trim().isEmpty()) {
                Price_Error.setText("Invalid. Cannot be empty.");
            } else if (!(isInteger(Price_Field.getText().trim()) || isDouble(Price_Field.getText().trim()))) {
                Price_Error.setText("Invalid. Must be number.");
            }
            Price_Error.setVisible(true);
            result = false;
        }
        return result;
    }

    void clearInputBoxes() {
        ModelID_Field.setText("");
        Make_Field.setText("");
        Name_Field.setText("");
        cmbType.setSelectedIndex(0);
        cmbColour.setSelectedIndex(0);
    }

    
    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
    
        int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this model?", "Confirm Update", JOptionPane.YES_NO_OPTION);
           if (confirmUpdate == JOptionPane.YES_OPTION)
           {
        // TODO add your handling code here:
        // verify input data
        // verify that new user does not currently exist
        try {
            // make the result set scrolable forward/backward updatable
            if (isValidData()) {
                // confirm if user wants to update or not
                
                String prepSQL = "UPDATE proj_models SET make = '"
                        + Make_Field.getText().trim()  + 
                        "', name = '"+ Name_Field.getText()+ 
                        "', Year = " + Year_Field.getText() +
                        ", colourid = " + cmbColour.getSelectedItem() +
                        ", typeid = " + cmbType.getSelectedItem() +
                        " WHERE modelid = " + ModelID_Field.getText().trim();

                int result = dbCon.executePrepared(prepSQL);
                
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("Model updated successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    getNewData();
                } else {
                    // check validation errors 
                }                
                
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating model. Restrictions apply" + e.getMessage());

        }
        
    }
    
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        
        // TODO add your handling code here:
        int confirmDelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this model?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if(confirmDelete == JOptionPane.YES_OPTION){
            //if user doesn't click yes, do nothing
            try {
            //Delete login user from table
            String prepSQL = "DELETE from proj_models WHERE modelid = " +  ModelID_Field.getText().trim();
            
            int result = dbCon.executePrepared(prepSQL);
            if (result > 0) {
                javax.swing.JLabel label = new javax.swing.JLabel("Model deleted successfully.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                getNewData();
            }
            }
            catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting Model. Restrictions apply ");
            System.out.println(e);
        } 

    }//GEN-LAST:event_btnDeleteUserActionPerformed
    }
    

    private void MoveNext() {
        // move result set to next record
        try {
            //if not the last row of the result set, move to next row
            if (!rs.isLast()) {

                rs.next();
                populateFields();

            }
        } catch (SQLException e) {
            Logger.getLogger(UpdateDeleteModels.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void MovePrevious() {
        // move result set to next record
        try {
            //if not the first row of the result set, move to previous row
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();

            }
        } catch (SQLException e) {
            Logger.getLogger(UpdateDeleteModels.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void cmbColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbColourActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Make_Error;
    private javax.swing.JTextField Make_Field;
    private javax.swing.JTextField ModelID_Field;
    private javax.swing.JLabel Name_Error;
    private javax.swing.JTextField Name_Field;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel Price_Error;
    private javax.swing.JTextField Price_Field;
    private javax.swing.JLabel Year_Error;
    private javax.swing.JTextField Year_Field;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cmbColour;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
