package jdbcgui;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class UpdateDeleteVehicles extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;

    ResultSet rs;

    public UpdateDeleteVehicles() { // ?
        initComponents();
        // center form in screen 
        //this.setLocationRelativeTo(null); // causing issue
        
        // set all error labels to invisible
        VIN_Error.setText("");
        VIN_Error.setVisible(false);
        
        try {//populate the user types 
            dbCon = new myDBCon();
            rs = dbCon.executeStatement("SELECT modelid FROM proj_models ORDER BY modelid ASC"); // CHANGE THIS
            while (rs.next()) {
                cmbModelID.addItem(rs.getString("modelid"));
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        // connect to db and get user data and populate form fields
        dbCon = new myDBCon();
        getNewData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        VIN_Field = new javax.swing.JTextField();
        cmbModelID = new javax.swing.JComboBox<>();
        btnUpdateUser = new javax.swing.JButton();
        VIN_Error = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Login User");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Vehicles");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ModelID:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("VIN:");

        VIN_Field.setEditable(false);
        VIN_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbModelID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbModelID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModelIDActionPerformed(evt);
            }
        });

        btnUpdateUser.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdateUser.setText("Update");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        VIN_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        VIN_Error.setForeground(new java.awt.Color(255, 0, 0));
        VIN_Error.setText("error label");

        btnDeleteUser.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDeleteUser.setText("Delete");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnPrevious)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VIN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VIN_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUpdateUser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeleteUser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNext))
                                    .addComponent(cmbModelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(VIN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VIN_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbModelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getNewData() {
        // get all user data and populate fields 
        try {
            rs = dbCon.executeStatement("SELECT vin, modelid FROM proj_vehicles ORDER BY vin ASC ");
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void populateFields() {
        // populate fields with the current user details 
         try {
            //populate fiels from ResultSet data
            VIN_Field.setText(rs.getString("vin"));
            cmbModelID.setSelectedItem(rs.getString("modelid"));

                
            EnableDisableButtons();
        } catch (SQLException e) {
            Logger.getLogger(UpdateDeleteVehicles.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }

    private void EnableDisableButtons() {
        // enable/disable Previous/Next buttons
         try {
            //enable previous and next if first and last row are not shown
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException e) {
            Logger.getLogger(UpdateDeleteVehicles.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    void clearErrorLabels() {
        // clear all error labels and set their visibility to false 
        VIN_Error.setText("");
        VIN_Error.setVisible(false);

    }



    boolean isValidData() {

        return true;
    }

    void clearInputBoxes() {
        VIN_Field.setText("");
        cmbModelID.setSelectedIndex(0);
    }

    
    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        try {
            // make the result set scrolable forward/backward updatable
          
                    if (isValidData()) {
                // confirm if user wants to update or not
                int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this vehicle?", "Confirm Update", JOptionPane.YES_NO_OPTION);
                if (confirmUpdate == JOptionPane.YES_OPTION)
                {
                    String prepSQL = "UPDATE proj_vehicles SET modelid = "
                            + cmbModelID.getSelectedItem()  
                           + " WHERE vin = "
                    + VIN_Field.getText().trim();

                    int result = dbCon.executePrepared(prepSQL);

                    if (result > 0) {

                        javax.swing.JLabel label = new javax.swing.JLabel("Vehicle updated successfully.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                        getNewData();
                    } else {
                        // check validation errors 
                    }                
                }
                
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
           
       
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating Vehicle. Updating is restricted" + e.getMessage());

        } 
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
        int confirmDelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this vehicle?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if(confirmDelete == JOptionPane.YES_OPTION){
            //if user doesn't click yes, do nothing
            try {
            //Delete login user from table
            String prepSQL = "DELETE FROM proj_vehicles WHERE vin = '" +  VIN_Field.getText().trim() + "'";
            
            int result = dbCon.executePrepared(prepSQL);
            if (result > 0) {
                javax.swing.JLabel label = new javax.swing.JLabel("Vehicle deleted successfully.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                getNewData();
            }
            }
            catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting Vehicle. Deletion is restricted.");
        } 
        }

    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void MoveNext() {
        // move result set to next record
        try {
            //if not the last row of the result set, move to next row
            if (!rs.isLast()) {

                rs.next();
                populateFields();

            }
        } catch (SQLException e) {
            Logger.getLogger(UpdateDeleteVehicles.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void MovePrevious() {
        // move result set to next record
        try {
            //if not the first row of the result set, move to previous row
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();

            }
        } catch (SQLException e) {
            Logger.getLogger(UpdateDeleteVehicles.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void cmbModelIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModelIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbModelIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VIN_Error;
    private javax.swing.JTextField VIN_Field;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cmbModelID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
