package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;
import static jdbcgui.DateValidator.isValidDateFormat;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class UpdateDeleteEmployee extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;
    ResultSet rsdeptno;
    ResultSet rsSex;

    /**
     * Creates new form AddEmployee
     */
    public UpdateDeleteEmployee() {
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        Empno_Error.setVisible(false);
        Fname_Error.setVisible(false);
        Bdate_Error.setVisible(false);
        Salary_Error.setVisible(false);
        Address_Error.setVisible(false);
        Lname_Error.setVisible(false);
        
        //rs = dbCon.executeStatement("SELECT deptno, dname FROM dept ORDER BY deptno ASC "); // TODO: CONFIRM w/ DR. WISSAM
        dbCon = new myDBCon();
        getNewData();
    }

    private void getNewData() {

        try {
            String str;
            // populate deptno field
            rs = dbCon.executeStatement("SELECT empid, fname, lname, address, sex, bdate, salary, dno FROM proj_employees ORDER BY empid ASC "); // TODO: CONFIRM w/ DR. WISSAM

            rsdeptno = dbCon.executeStatement("SELECT deptno, dname FROM dept ORDER BY deptno ASC "); // TODO: CONFIRM w/ DR. WISSAM
//            rsdeptno = statement.executeQuery("SELECT deptno, dname FROM dept ORDER BY deptno ASC ");
            cmbDno.removeAllItems();
            while (rsdeptno.next()) {
                cmbDno.addItem(rsdeptno.getString("deptno"));
            }
            
            rsSex = dbCon.executeStatement("SELECT unique sex from proj_employees order by sex asc"); // TODO: CONFIRM w/ DR. WISSAM
            cmbSex.removeAllItems();
            while (rsSex.next()) {
                cmbSex.addItem(rsSex.getString("sex"));
            }

            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected empid.");
            System.out.println(e);
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        Fname_Error = new javax.swing.JLabel();
        Bdate_Error = new javax.swing.JLabel();
        Salary_Error = new javax.swing.JLabel();
        Address_Error = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lname_Error = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EmpID_Field = new javax.swing.JTextField();
        Fname_Field = new javax.swing.JTextField();
        Lname_Field = new javax.swing.JTextField();
        Salary_Field = new javax.swing.JTextField();
        Address_Field = new javax.swing.JTextField();
        cmbDno = new javax.swing.JComboBox<>();
        BDate_Field = new javax.swing.JFormattedTextField();
        Empno_Error = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Employee");

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        Fname_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Fname_Error.setForeground(new java.awt.Color(255, 0, 0));
        Fname_Error.setText("error label");

        Bdate_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Bdate_Error.setForeground(new java.awt.Color(255, 0, 0));
        Bdate_Error.setText("error label");

        Salary_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Salary_Error.setForeground(new java.awt.Color(255, 0, 0));
        Salary_Error.setText("error label");

        Address_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Address_Error.setForeground(new java.awt.Color(255, 0, 0));
        Address_Error.setText("error label");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("SEX:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("EMPID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("FNAME:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LNAME:");

        Lname_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Lname_Error.setForeground(new java.awt.Color(255, 0, 0));
        Lname_Error.setText("error label");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DNO:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("BDATE:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("SALARY:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ADDRESS:");

        EmpID_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpID_FieldActionPerformed(evt);
            }
        });

        Fname_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Lname_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lname_FieldActionPerformed(evt);
            }
        });

        Salary_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Address_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbDno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbDno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDnoActionPerformed(evt);
            }
        });

        BDate_Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MMM-yyyy"))));
        BDate_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Empno_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Empno_Error.setForeground(new java.awt.Color(255, 0, 0));
        Empno_Error.setText("error label");

        cmbSex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Fname_Field)
                                    .addComponent(Lname_Field)
                                    .addComponent(Address_Field)
                                    .addComponent(Salary_Field)
                                    .addComponent(cmbDno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BDate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Fname_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bdate_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Salary_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Address_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lname_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmpID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Empno_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EmpID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Empno_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Fname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Lname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BDate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdate_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Salary_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salary_Error))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            EmpID_Field.setText(rs.getString("empid"));
            Fname_Field.setText(rs.getString("fname"));
            Lname_Field.setText(rs.getString("lname"));
            
            BDate_Field.setText(rs.getString("bdate"));
            Salary_Field.setText(rs.getString("salary"));
            Address_Field.setText(rs.getString("address"));
            cmbSex.setSelectedItem(rs.getString("sex"));
            cmbDno.setSelectedItem(rs.getString("dno"));
            
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() {
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void MovePrevious() {
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this employee?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
           if (confirmUpdate == JOptionPane.YES_OPTION)
           {
        try {
            
                     // make the result set scrolable forward/backward updatable
            String prepSQL = "DELETE proj_employees WHERE empid = " + EmpID_Field.getText().trim();
            int result = dbCon.executePrepared(prepSQL);
            if (result > 0) {
                javax.swing.JLabel label = new javax.swing.JLabel("Employee No " + EmpID_Field.getText().trim() + " deleted successfully.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                getNewData();
            }
              
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new employee.");
        }
           
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    void clearErrorLabels() {
        Empno_Error.setText("");
        Empno_Error.setVisible(false);
        Fname_Error.setText("");
        Fname_Error.setVisible(false);
        Lname_Error.setText("");
        Lname_Error.setVisible(false);
        Bdate_Error.setText("");
        Bdate_Error.setVisible(false);
        Salary_Error.setText("");
        Salary_Error.setVisible(false);
        Address_Error.setText("");
        Address_Error.setVisible(false);
    }

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    boolean isValidData() {
        clearErrorLabels();
        boolean result = true;
        if (EmpID_Field.getText().trim().isEmpty() || !isInteger(EmpID_Field.getText().trim())) {
            if (EmpID_Field.getText().trim().isEmpty()) {
                Empno_Error.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(EmpID_Field.getText().trim())) {
                Empno_Error.setText("Invalid. Must be integer.");
            }
            Empno_Error.setVisible(true);
            result = false;
        }
        if (Fname_Field.getText().trim().isEmpty() || (Fname_Field.getText().trim().length() > 10)) {
            if (Fname_Field.getText().trim().isEmpty()) {
                Fname_Error.setText("Invalid. Cannot be empty.");
            } else if ((Fname_Field.getText().trim().length() > 10)) {
                Fname_Error.setText("Invalid. Must be < 10 chars.");
            }

            Fname_Error.setVisible(true);
            result = false;
        }

        if (Lname_Field.getText().trim().isEmpty() || (Lname_Field.getText().trim().length() > 10)) {
            if (Fname_Field.getText().trim().isEmpty()) {
                Lname_Error.setText("Invalid. Cannot be empty.");
            } else if ((Fname_Field.getText().trim().length() > 10)) {
                Lname_Error.setText("Invalid. Must be < 10 chars.");
            }

            Lname_Error.setVisible(true);
            result = false;
        }

        if (Address_Field.getText().trim().isEmpty() || (Address_Field.getText().trim().length() > 9)) {
            if (Address_Field.getText().trim().isEmpty()) {
                Address_Error.setText("Invalid. Cannot be empty.");
            } else if (Address_Field.getText().trim().length() > 9) {
                Address_Error.setText("Invalid. Must be < 9 chars.");
            }
            Address_Error.setVisible(true);
            result = false;
        }

        if (BDate_Field.getText().trim().isEmpty() || !isValidDateFormat(BDate_Field.getText())) {
            if (BDate_Field.getText().trim().isEmpty()) {
                Bdate_Error.setText("Invalid. Cannot be empty.");
            } else if (!isValidDateFormat(BDate_Field.getText())) {
                Bdate_Error.setText("Invalid. Must be number.");
            }
            result = false;
        }

        if (Salary_Field.getText().trim().isEmpty() || !(isInteger(Salary_Field.getText().trim()) || isDouble(Salary_Field.getText().trim()))) {
            if (Salary_Field.getText().trim().isEmpty()) {
                Salary_Error.setText("Invalid. Cannot be empty.");
            } else if (!(isInteger(Salary_Field.getText().trim()) || isDouble(Salary_Field.getText().trim()))) {
                Salary_Error.setText("Invalid. Must be number.");
            }

            Salary_Error.setVisible(true);
            result = false;
        }

       
        return result;
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try {
            // make the result set scrolable forward/backward updatable
            int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this employee?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
           if (confirmUpdate == JOptionPane.YES_OPTION)
           {
                if (isValidData()) {
                String prepSQL = "UPDATE proj_employees SET fname = " + 
                        "'" + Fname_Field.getText().trim().toUpperCase() + 
                        "', lname = '" + Lname_Field.getText().trim().toUpperCase() + 
                        ", bdate = '" + BDate_Field.getText() + 
                        "', salary = " + Salary_Field.getText().trim() + 
                        ", address = " + Address_Field.getText().trim() + 
                        ", sex = " + cmbSex.getSelectedItem() + 
                        ", dno = " + cmbDno.getSelectedItem() + 
                        " WHERE empid = " + EmpID_Field.getText().trim();
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    String successMessage = "Employee No " + EmpID_Field.getText() + " has been updated successfully.";
                    javax.swing.JLabel label = new javax.swing.JLabel(successMessage);
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "Success", JOptionPane.INFORMATION_MESSAGE);

                    getNewData();

                } else {
                    // check validation errors 
                }
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }
           }
           
           
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating employee." + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void EmpID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpID_FieldActionPerformed

    private void Lname_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lname_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lname_FieldActionPerformed

    private void cmbDnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDnoActionPerformed

    private void cmbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_Error;
    private javax.swing.JTextField Address_Field;
    private javax.swing.JFormattedTextField BDate_Field;
    private javax.swing.JLabel Bdate_Error;
    private javax.swing.JTextField EmpID_Field;
    private javax.swing.JLabel Empno_Error;
    private javax.swing.JLabel Fname_Error;
    private javax.swing.JTextField Fname_Field;
    private javax.swing.JLabel Lname_Error;
    private javax.swing.JTextField Lname_Field;
    private javax.swing.JLabel Salary_Error;
    private javax.swing.JTextField Salary_Field;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDno;
    private javax.swing.JComboBox<String> cmbSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
