package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;
import static jdbcgui.DateValidator.isValidDateFormat;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class UpdateDeleteSales extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;
    ResultSet rsVIN;
    ResultSet rsEmp;

    /**
     * Creates new form AddEmployee
     */
    public UpdateDeleteSales() {
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        SaleID_Error.setVisible(false);
        Warranty_Error.setVisible(false);
        SDate_Error.setVisible(false);
        
        //rs = dbCon.executeStatement("SELECT deptno, dname FROM dept ORDER BY deptno ASC "); // TODO: CONFIRM w/ DR. WISSAM
        dbCon = new myDBCon();
        getNewData();
    }

    private void getNewData() {

        try {
            String str;
            // populate deptno field
            rs = dbCon.executeStatement("SELECT SALEid, VIN, SDATE, WARRANTYYEARS, EMPID FROM proj_SALES ORDER BY SALEID ASC "); // TODO: CONFIRM w/ DR. WISSAM

            rsVIN = dbCon.executeStatement("SELECT vin FROM PROJ_vehicles ORDER BY vin ASC "); // TODO: CONFIRM w/ DR. WISSAM
//            rsdeptno = statement.executeQuery("SELECT deptno, dname FROM dept ORDER BY deptno ASC ");
            cmbVIN.removeAllItems();
            while (rsVIN.next()) {
                cmbVIN.addItem(rsVIN.getString("vin"));
            }
            
            rsEmp = dbCon.executeStatement("SELECT EMPID FROM PROJ_EMPLOYEES ORDER BY EMPID ASC "); // TODO: CONFIRM w/ DR. WISSAM
            cmbEmpID.removeAllItems();
            while (rsEmp.next()) {
                cmbEmpID.addItem(rsEmp.getString("empid"));
            }

            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected sale.");
            System.out.println(e);
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        Warranty_Error = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SDate_Error = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SaleID_Field = new javax.swing.JTextField();
        Warranty_Field = new javax.swing.JTextField();
        SDate_Field = new javax.swing.JTextField();
        cmbVIN = new javax.swing.JComboBox<>();
        SaleID_Error = new javax.swing.JLabel();
        cmbEmpID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Sales");

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        Warranty_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Warranty_Error.setForeground(new java.awt.Color(255, 0, 0));
        Warranty_Error.setText("error label");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("EMPID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("SALEID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("WARRANTY:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("SDATE:");

        SDate_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        SDate_Error.setForeground(new java.awt.Color(255, 0, 0));
        SDate_Error.setText("error label");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("VIN:");

        SaleID_Field.setEditable(false);
        SaleID_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaleID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleID_FieldActionPerformed(evt);
            }
        });

        Warranty_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SDate_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SDate_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDate_FieldActionPerformed(evt);
            }
        });

        cmbVIN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVINActionPerformed(evt);
            }
        });

        SaleID_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        SaleID_Error.setForeground(new java.awt.Color(255, 0, 0));
        SaleID_Error.setText("error label");

        cmbEmpID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SaleID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SaleID_Error, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Warranty_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(SDate_Field)
                                    .addComponent(cmbVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SDate_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Warranty_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SaleID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaleID_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Warranty_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Warranty_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SDate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDate_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            SaleID_Field.setText(rs.getString("saleid"));
            Warranty_Field.setText(rs.getString("warrantyyears"));
            SDate_Field.setText(rs.getString("sdate"));
            cmbEmpID.setSelectedItem(rs.getString("empid"));
            cmbVIN.setSelectedItem(rs.getString("vin"));
            
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() {
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void MovePrevious() {
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:\
        int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this sale?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
           if (confirmUpdate == JOptionPane.YES_OPTION)
           {
                       try {
            // make the result set scrolable forward/backward updatable
            String prepSQL = "DELETE proj_sales WHERE saleid = " + SaleID_Field.getText().trim();
            int result = dbCon.executePrepared(prepSQL);
            if (result > 0) {
                javax.swing.JLabel label = new javax.swing.JLabel("Sale No " + SaleID_Field.getText().trim() + " deleted successfully.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                getNewData();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting Sale. Deletion is restricted");
            System.out.println(e);
        }
           }

    }//GEN-LAST:event_btnDeleteActionPerformed

    void clearErrorLabels() {
        SaleID_Error.setText("");
        SaleID_Error.setVisible(false);
        Warranty_Error.setText("");
        Warranty_Error.setVisible(false);
        SDate_Error.setText("");
        SDate_Error.setVisible(false);
    }

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    boolean isValidData() {
        clearErrorLabels();
        boolean result = true;
        // you need to check format deails and make sure they are consistent with DB 
        if (SaleID_Field.getText().trim().isEmpty() || !isInteger(SaleID_Field.getText().trim())) {
            if (SaleID_Field.getText().trim().isEmpty()) {
                SaleID_Error.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(SaleID_Field.getText().trim())) {
                SaleID_Error.setText("Invalid. Must be integer.");
            }
            SaleID_Error.setVisible(true);
            result = false;
        }

        if (SDate_Field.getText().trim().isEmpty() || !isValidDateFormat(SDate_Field.getText())) {
            if (SDate_Field.getText().trim().isEmpty()){
            SDate_Error.setText("Invalid. Cannot be empty.");
            SDate_Error.setVisible(true);
            } else if (!isValidDateFormat(SDate_Field.getText())){
                SDate_Error.setText("Invalid. Date must be DD-MMM-YYYY.");
                SDate_Error.setVisible(true);
            }
            result = false;
        }


        if (Warranty_Field.getText().trim().isEmpty()) {
            Warranty_Error.setText("Invalid. Cannot be empty.");
            Warranty_Error.setVisible(true);
            result = false;
        }

     
     
    
        return result;
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try {
           int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this sale?", "Confirm Update", JOptionPane.YES_NO_OPTION);
           if (confirmUpdate == JOptionPane.YES_OPTION)
           {
                  if (isValidData()) {
                String prepSQL = "UPDATE proj_sales SET warrantyyears = " + 
                        Warranty_Field.getText().trim().toUpperCase() + 
                        ", sdate = '" + SDate_Field.getText().trim().toUpperCase() + 
                        "', empid = " + cmbEmpID.getSelectedItem() + 
                        ", vin = " + cmbVIN.getSelectedItem() + 
                        " WHERE saleid = " + SaleID_Field.getText().trim();
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    String successMessage = "Sale No " + SaleID_Field.getText() + " has been updated successfully.";
                    javax.swing.JLabel label = new javax.swing.JLabel(successMessage);
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "Success", JOptionPane.INFORMATION_MESSAGE);

                    getNewData();

                } else {
                    // check validation errors 
                }
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }
           }
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating sale. Update is restricted." + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void SaleID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaleID_FieldActionPerformed

    private void SDate_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDate_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SDate_FieldActionPerformed

    private void cmbVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVINActionPerformed

    private void cmbEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SDate_Error;
    private javax.swing.JTextField SDate_Field;
    private javax.swing.JLabel SaleID_Error;
    private javax.swing.JTextField SaleID_Field;
    private javax.swing.JLabel Warranty_Error;
    private javax.swing.JTextField Warranty_Field;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbEmpID;
    private javax.swing.JComboBox<String> cmbVIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
