/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmer
 */
public class UpdateDeleteCustomer extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;
    ResultSet rsCustno;
    
    /**
     * Creates new form UpdateDeleteCustomer
     */
    public UpdateDeleteCustomer() {
        initComponents();
        
        CustomerID_Error.setVisible(false);
        Fname_Error.setVisible(false);
        Lname_Error.setVisible(false);
        Address_Error.setVisible(false);
        Email_Error.setVisible(false);
        PhoneNo_Error.setVisible(false);
        dbCon = new myDBCon();
        
        getNewData();
    }

    private void getNewData() {

        try {
            String str;
            // populate deptno field
            rs = dbCon.executeStatement("SELECT customerID, cfname, clname, address, sex, email, phoneNo FROM proj_customers ORDER BY customerID ASC"); 
            rsCustno = dbCon.executeStatement("SELECT unique sex FROM proj_customers ORDER BY sex ASC"); // TODO: CONFIRM w/ DR. WISSAM
//            rsdeptno = statement.executeQuery("SELECT deptno, dname FROM dept ORDER BY deptno ASC ");
            cmbSex.removeAllItems();
            while (rsCustno.next()) {
                cmbSex.addItem(rsCustno.getString("sex"));
            }

            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected customerID.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void populateFields() {
        try {
            CustomerID_Field.setText(rs.getString("customerid"));
            Fname_Field.setText(rs.getString("cfname"));
            Lname_Field.setText(rs.getString("clname"));
            Address_Field.setText(rs.getString("Address"));
            cmbSex.setSelectedItem(rs.getString("sex"));
            Email_Field.setText(rs.getString("Email"));
            PhoneNo_Field.setText(rs.getString("PhoneNo"));
            
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        private void MoveNext() {
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
                                

    private void MovePrevious() {
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
                                     
 
    
    
    void clearErrorLabels() {
        CustomerID_Error.setText("");
        Fname_Error.setText("");
        Lname_Error.setText("");
        Address_Error.setText("");
        Email_Error.setText("");
        PhoneNo_Error.setText("");
    }

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
     private boolean isValidEmail(String email) throws SQLException {
        boolean isValidEmail = false;
        // write code here
        Pattern pattern = Pattern.compile(".+@.+\\..+");
        Matcher matcher = pattern.matcher(email);
        isValidEmail = matcher.matches();

        return isValidEmail;
    }

    private boolean isValidPhone(String phone) throws SQLException {
        boolean isValidPhone = false;
        // write code here
        Pattern pattern = Pattern.compile("\\+\\d+\\s+\\d+");
        Matcher matcher = pattern.matcher(phone);
        isValidPhone = matcher.matches();

        return isValidPhone;
    }
    
    boolean isValidData() throws SQLException {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
       

        if (Fname_Field.getText().trim().isEmpty() || (Fname_Field.getText().trim().length() > 15)) {
            if (Fname_Field.getText().trim().isEmpty()) {
                Fname_Error.setText("Invalid. Cannot be empty.");
            } else if ((Fname_Field.getText().trim().length() > 15)) {
                Fname_Error.setText("Invalid. Must be < 15 chars.");
            }
            Fname_Error.setVisible(true);
            result = false;
        }

        if (Lname_Field.getText().trim().isEmpty() || (Lname_Field.getText().trim().length() > 15)) {
            if (Lname_Field.getText().trim().isEmpty()) {
                Lname_Error.setText("Invalid. Cannot be empty.");
            } else if ((Lname_Field.getText().trim().length() > 15)) {
                Lname_Error.setText("Invalid. Must be < 15 chars.");
            }
            Lname_Error.setVisible(true);
            result = false;
        }

        if (Address_Field.getText().trim().isEmpty() || (Address_Field.getText().trim().length() > 100)) {
            if (Address_Field.getText().trim().isEmpty()) {
                Address_Error.setText("Invalid. Cannot be empty.");
            } else if (Address_Field.getText().trim().length() > 100) {
                Address_Error.setText("Invalid. Must be < 100 chars.");
            }
            Address_Error.setVisible(true);
            result = false;
        }
        
        if (Email_Field.getText().trim().isEmpty() || !isValidEmail(Email_Field.getText())) {
            if (Email_Field.getText().trim().isEmpty()) {
                Email_Error.setText("Invalid. Cannot be empty.");
            } else if (!isValidEmail(Email_Field.getText())){
                Email_Error.setText("Email format must be like example@example.com");
            }
            Email_Error.setVisible(true);
            result = false;
        }
                
        if (PhoneNo_Field.getText().trim().isEmpty() || !isValidPhone(PhoneNo_Field.getText()) ) {
            if (PhoneNo_Field.getText().trim().isEmpty()) {
                PhoneNo_Error.setText("Invalid. Cannot be empty.");     
            } else if (!isValidPhone(PhoneNo_Field.getText())){
                PhoneNo_Error.setText("phone number must be like +xxx xxxxxxx");
            }
            PhoneNo_Error.setVisible(true);
            result = false;
        }

        return result;
    }
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Email_Error = new javax.swing.JLabel();
        Lname_Field = new javax.swing.JTextField();
        PhoneNo_Error = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Address_Field = new javax.swing.JTextField();
        CustomerID_Label = new javax.swing.JLabel();
        Email_Field = new javax.swing.JTextField();
        Fname_Label = new javax.swing.JLabel();
        PhoneNo_Field = new javax.swing.JTextField();
        Lname_Label = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox<>();
        Address_Label = new javax.swing.JLabel();
        CustomerID_Error = new javax.swing.JLabel();
        Sex_Label = new javax.swing.JLabel();
        Fname_Error = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Lname_Error = new javax.swing.JLabel();
        PhoneNo_Label = new javax.swing.JLabel();
        Address_Error = new javax.swing.JLabel();
        CustomerID_Field = new javax.swing.JTextField();
        Fname_Field = new javax.swing.JTextField();
        btnPrevious = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Email_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Email_Error.setForeground(new java.awt.Color(255, 0, 0));
        Email_Error.setText("error label");

        Lname_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lname_FieldActionPerformed(evt);
            }
        });

        PhoneNo_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        PhoneNo_Error.setForeground(new java.awt.Color(255, 0, 0));
        PhoneNo_Error.setText("error label");

        Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Title.setText("Update/Delete Customer");

        Address_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Address_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address_FieldActionPerformed(evt);
            }
        });

        CustomerID_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CustomerID_Label.setText("CUSTOMER ID:");

        Email_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_FieldActionPerformed(evt);
            }
        });

        Fname_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Fname_Label.setText("FIRST NAME:");

        PhoneNo_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PhoneNo_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNo_FieldActionPerformed(evt);
            }
        });

        Lname_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lname_Label.setText("LAST NAME:");

        cmbSex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Address_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Address_Label.setText("ADDRESS:");

        CustomerID_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        CustomerID_Error.setForeground(new java.awt.Color(255, 0, 0));
        CustomerID_Error.setText("error label");

        Sex_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sex_Label.setText("SEX:");

        Fname_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Fname_Error.setForeground(new java.awt.Color(255, 0, 0));
        Fname_Error.setText("error label");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("EMAIL:");

        Lname_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Lname_Error.setForeground(new java.awt.Color(255, 0, 0));
        Lname_Error.setText("error label");

        PhoneNo_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PhoneNo_Label.setText("PHONE NUMBER:");

        Address_Error.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Address_Error.setForeground(new java.awt.Color(255, 0, 0));
        Address_Error.setText("error label");

        CustomerID_Field.setEditable(false);
        CustomerID_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CustomerID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerID_FieldActionPerformed(evt);
            }
        });

        Fname_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fname_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fname_FieldActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PhoneNo_Label)
                    .addComponent(Fname_Label)
                    .addComponent(CustomerID_Label)
                    .addComponent(Lname_Label)
                    .addComponent(Address_Label)
                    .addComponent(Sex_Label)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerID_Field)
                    .addComponent(Fname_Field)
                    .addComponent(Lname_Field)
                    .addComponent(Address_Field)
                    .addComponent(Email_Field)
                    .addComponent(PhoneNo_Field)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustomerID_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addComponent(Fname_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lname_Error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Address_Error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Email_Error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PhoneNo_Error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerID_Label)
                    .addComponent(CustomerID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerID_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fname_Label)
                    .addComponent(Fname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname_Label)
                    .addComponent(Lname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address_Label)
                    .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex_Label)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNo_Label)
                    .addComponent(PhoneNo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNo_Error))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lname_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lname_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lname_FieldActionPerformed

    private void Address_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Address_FieldActionPerformed

    private void Email_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_FieldActionPerformed

    private void PhoneNo_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNo_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNo_FieldActionPerformed

    private void CustomerID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerID_FieldActionPerformed

    private void Fname_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fname_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fname_FieldActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this customer?", "Confirm Update", JOptionPane.YES_NO_OPTION);
           if (confirmUpdate == JOptionPane.YES_OPTION)
           {
        try {
           
                       if (isValidData()) {
                String prepSQL = "UPDATE proj_customers SET cfname = " +
                "'" + Fname_Field.getText() +
                "', clname = '" +  Lname_Field.getText() +
                "', address = '" + Address_Field.getText() +
                "', sex = '" + cmbSex.getSelectedItem() +
                "' , email = '" +  Email_Field.getText().trim() +
                "' , phoneno = '" + PhoneNo_Field.getText().trim() +
                "' WHERE customerid = " +  CustomerID_Field.getText().trim();
                System.out.println(prepSQL);

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    String successMessage = "Custoemr No " + CustomerID_Field.getText() + " has been updated successfully.";
                    javax.swing.JLabel label = new javax.swing.JLabel(successMessage);
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "Success", JOptionPane.INFORMATION_MESSAGE);

                    getNewData();

                } else {
                    // check validation errors
                }
                //                prepStatement.close();
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

           
    
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating customer." + e.getMessage());

        }
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
              int confirmUpdate = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this customer?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
           if (confirmUpdate == JOptionPane.YES_OPTION)
           {
               
           }
        try {
            // make the result set scrolable forward/backward updatable
            String prepSQL = "DELETE proj_customers WHERE customerid = " + CustomerID_Field.getText().trim();
            int result = dbCon.executePrepared(prepSQL);
            if (result > 0) {
                javax.swing.JLabel label = new javax.swing.JLabel("Customer No " + CustomerID_Field.getText().trim() + " deleted successfully.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                getNewData();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting an customer. Restrictions apply");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDeleteCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_Error;
    private javax.swing.JTextField Address_Field;
    private javax.swing.JLabel Address_Label;
    private javax.swing.JLabel CustomerID_Error;
    private javax.swing.JTextField CustomerID_Field;
    private javax.swing.JLabel CustomerID_Label;
    private javax.swing.JLabel Email_Error;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JLabel Fname_Error;
    private javax.swing.JTextField Fname_Field;
    private javax.swing.JLabel Fname_Label;
    private javax.swing.JLabel Lname_Error;
    private javax.swing.JTextField Lname_Field;
    private javax.swing.JLabel Lname_Label;
    private javax.swing.JLabel PhoneNo_Error;
    private javax.swing.JTextField PhoneNo_Field;
    private javax.swing.JLabel PhoneNo_Label;
    private javax.swing.JLabel Sex_Label;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSex;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
